block.2=water

# all foliage (exclusion from edge detection)
# grass, ground petals ### flowers ### leaves ### water stoof
block.3=pink_petals dead_bush vines glow_berries spore_blossom nether_sprouts crimson_fungus short_grass bush tall_grass fern large_fern dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower lily_of_the_valley wither_rose torchflower eyeblossom sunflower lilac rose_bush peony pitcher_plant oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves mangrove_leaves cherry_leaves pale_oak_leaves azalea_leaves flowering_azalea_leaves kelp seagrass

block.4=short_grass