clouds=off

screen = CUSTOM_LIGHTING FOG_ON EDGE_DETECTION CHROMATIC_ABERRATION BLOOM_ON <empty> <empty> <empty> <empty> <empty> <empty> [ADVANCED]

screen.ADVANCED.columns = 2
screen.ADVANCED = [LIGHTING_OPTIONS] [FOG_OPTIONS] [ABERRATION_OPTIONS] [EDGE_DETECTION_OPTIONS] [BLOOM_OPTIONS]

screen.LIGHTING_OPTIONS.columns = 2
screen.LIGHTING_OPTIONS = SHADOW_RADIUS SHADOW_RANGE

screen.FOG_OPTIONS.columns = 2
screen.FOG_OPTIONS = FOG_DENSITY

screen.ABERRATION_OPTIONS.columns = 2
screen.ABERRATION_OPTIONS = CHROMATIC_ABERRATION_STRENGTH

screen.EDGE_DETECTION_OPTIONS.columns = 2
screen.EDGE_DETECTION_OPTIONS = EDGE_DETECTION_STRENGTH EDGE_SIZE

screen.BLOOM_OPTIONS.columns = 2
screen.BLOOM_OPTIONS = BLOOM_THRESHOLD

sliders = CHROMATIC_ABERRATION_STRENGTH BLOOM_THRESHOLD SHADOW_RADIUS SHADOW_RANGE EDGE_SIZE EDGE_DETECTION_STRENGTH