screen = CHROMATIC_ABERRATION EDGE_DETECTION [ADVANCED]

screen.ADVANCED.columns = 2
screen.ADVANCED = [ABERRATION_OPTIONS] [EDGE_DETECTION_OPTIONS] [BLOOM_OPTIONS]

screen.ABERRATION_OPTIONS.columns = 2
screen.ABERRATION_OPTIONS = CHROMATIC_ABERRATION_STRENGTH

screen.EDGE_DETECTION_OPTIONS.columns = 2

screen.BLOOM_OPTIONS.columns = 2
screen.BLOOM_OPTIONS = BLOOM_THRESHOLD

sliders = CHROMATIC_ABERRATION_STRENGTH BLOOM_THRESHOLD