clouds=off

screen = CUSTOM_LIGHTING FOG_ON EDGE_DETECTION CHROMATIC_ABERRATION BLOOM_ON COLOR_MAPPING FXAA_ENABLED SSAO_ENABLED <empty> <empty> <empty> <empty> <empty> [ADVANCED]

screen.ADVANCED.columns = 2
screen.ADVANCED = [LIGHTING_OPTIONS] [FOG_OPTIONS] [ABERRATION_OPTIONS] [EDGE_DETECTION_OPTIONS] [BLOOM_OPTIONS] [FXAA_OPTIONS] [SSAO_OPTIONS] [ENVIRONMENT_OPTIONS]

screen.LIGHTING_OPTIONS.columns = 2
screen.LIGHTING_OPTIONS = SHADOW_RADIUS SHADOW_RANGE

screen.FOG_OPTIONS.columns = 2
screen.FOG_OPTIONS = FOG_DENSITY

screen.ABERRATION_OPTIONS.columns = 2
screen.ABERRATION_OPTIONS = CHROMATIC_ABERRATION_STRENGTH

screen.EDGE_DETECTION_OPTIONS.columns = 2
screen.EDGE_DETECTION_OPTIONS = EDGE_DETECTION_MODE EDGE_DETECTION_STRENGTH EDGE_SIZE EDGE_BRIGHTNESS EXCLUDE_ENTITIES EXCLUDE_FOLIAGE

screen.BLOOM_OPTIONS.columns = 2
screen.BLOOM_OPTIONS = BLOOM_THRESHOLD

screen.FXAA_OPTIONS.columns = 2

screen.SSAO_OPTIONS.columns = 2

screen.ENVIRONMENT_OPTIONS.columns = 2
screen.ENVIRONMENT_OPTIONS = WAVING_WATER WAVING_FOLIAGE

sliders = CHROMATIC_ABERRATION_STRENGTH BLOOM_THRESHOLD SHADOW_RADIUS SHADOW_RANGE EDGE_SIZE EDGE_DETECTION_STRENGTH EDGE_BRIGHTNESS